

import json

pic_dir = 'static/picture/'

with open("data/members.json" , encoding='utf_8') as json_file:
    idol_json = json.load(json_file)
    json_file.close()

with open("data/group.json" , encoding='utf_8') as json_file:
    group_json = json.load(json_file)
    json_file.close()

class Point():

    def __init__(self) -> None:
        self.idol_group_point = {
            "μ's": 0,
            "Aqours": 0,
            "Saint Snow": 0,
            "虹ヶ咲学園スクールアイドル同好会": 0,
            "Liella": 0
        }
        self.idol_group = {
            "μ's": "",
            "Aqours": "",
            "Saint Snow": "",
            "虹ヶ咲学園スクールアイドル同好会": "",
            "Liella": ""
        }
        self.idol_color_group = {
            "μ's_c": "",
            "Aqours_c": "",
            "Saint Snow_c": "",
            "虹ヶ咲学園スクールアイドル同好会_c": "",
            "Liella_c": ""
        }
        self.idol_dic = {
            "Aida_Rikako": "",
            "Furihata_Ai": "",
            "Iida_Riho": "",
            "Inami_Anju": "",
            "Kobayashi_Aika": "",
            "Komiya_Arisa": "",
            "Kubo_Yurika": "",
            "Kusuda_Aina": "",
            "Mimori_Suzuko": "",
            "Nanjo_Yoshino": "",
            "Nitta_Emi": "",
            "Pile": "",
            "Saito_Shuka": "",
            "Suwa_Nanaka": "",
            "Suzuki_Aina": "",
            "Takatsuki_Kanako": "",
            "Tokui_Sora": "",
            "Uchida_Aya": "",
            "Sato_Hinata": "",
            "Tano_Asami": "",
            "Onishi_Aguri": "",
            "Sagara_Mayu": "",
            "Maeda_Kaori": "",
            "Kubota_Miyu": "",
            "Murakami_Natsumi": "",
            "Kito_Akari": "",
            "Kusunoki_Tomori": "",
            "Sashide_Maria": "",
            "Tanaka_Chiemi": "",
            "Koizumi_Moeka": "",
            "Uchida_Shu": "",
            "Houmoto_Akina": "",
            "Yano_Hinaki": "",
            "Date_Sayuri": "",
            "Liyuu": "",
            "Misaki_Nako": "",
            "Payton_Naomi": "",
            "Aoyama_Nagisa": "",
        }
        self.idol_color_dic = {
            "Aida_Rikako_c": "",
            "Furihata_Ai_c": "",
            "Iida_Riho_c": "",
            "Inami_Anju_c": "",
            "Kobayashi_Aika_c": "",
            "Komiya_Arisa_c": "",
            "Kubo_Yurika_c": "",
            "Kusuda_Aina_c": "",
            "Mimori_Suzuko_c": "",
            "Nanjo_Yoshino_c": "",
            "Nitta_Emi_c": "",
            "Pile_c": "",
            "Saito_Shuka_c": "",
            "Suwa_Nanaka_c": "",
            "Suzuki_Aina_c": "",
            "Takatsuki_Kanako_c": "",
            "Tokui_Sora_c": "",
            "Uchida_Aya_c": "",
            "Sato_Hinata_c": "",
            "Tano_Asami_c": "",
            "Onishi_Aguri_c": "",
            "Sagara_Mayu_c": "",
            "Maeda_Kaori_c": "",
            "Kubota_Miyu_c": "",
            "Murakami_Natsumi_c": "",
            "Kito_Akari_c": "",
            "Kusunoki_Tomori_c": "",
            "Sashide_Maria_c": "",
            "Tanaka_Chiemi_c": "",
            "Koizumi_Moeka_c": "",
            "Uchida_Shu_c": "",
            "Houmoto_Akina_c": "",
            "Yano_Hinaki_c": "",
            "Date_Sayuri_c": "",
            "Liyuu_c": "",
            "Misaki_Nako_c": "",
            "Payton_Naomi_c": "",
            "Aoyama_Nagisa_c": "",

            "Aida_Rikako_rc": "",
            "Furihata_Ai_rc": "",
            "Iida_Riho_rc": "",
            "Inami_Anju_rc": "",
            "Kobayashi_Aika_rc": "",
            "Komiya_Arisa_rc": "",
            "Kubo_Yurika_rc": "",
            "Kusuda_Aina_rc": "",
            "Mimori_Suzuko_rc": "",
            "Nanjo_Yoshino_rc": "",
            "Nitta_Emi_rc": "",
            "Pile_rc": "",
            "Saito_Shuka_rc": "",
            "Suwa_Nanaka_rc": "",
            "Suzuki_Aina_rc": "",
            "Takatsuki_Kanako_rc": "",
            "Tokui_Sora_rc": "",
            "Uchida_Aya_rc": "",
            "Sato_Hinata_rc": "",
            "Tano_Asami_rc": "",
            "Onishi_Aguri_rc": "",
            "Sagara_Mayu_rc": "",
            "Maeda_Kaori_rc": "",
            "Kubota_Miyu_rc": "",
            "Murakami_Natsumi_rc": "",
            "Kito_Akari_rc": "",
            "Kusunoki_Tomori_rc": "",
            "Sashide_Maria_rc": "",
            "Tanaka_Chiemi_rc": "",
            "Koizumi_Moeka_rc": "",
            "Uchida_Shu_rc": "",
            "Houmoto_Akina_rc": "",
            "Yano_Hinaki_rc": "",
            "Date_Sayuri_rc": "",
            "Liyuu_rc": "",
            "Misaki_Nako_rc": "",
            "Payton_Naomi_rc": "",
            "Aoyama_Nagisa_rc": ""
        }
        self.idol_ins_dic = {
            "Aida_Rikako_i": "",
            "Furihata_Ai_i": "",
            "Iida_Riho_i": "",
            "Inami_Anju_i": "",
            "Kobayashi_Aika_i": "",
            "Komiya_Arisa_i": "",
            "Kubo_Yurika_i": "",
            "Kusuda_Aina_i": "",
            "Mimori_Suzuko_i": "",
            "Nanjo_Yoshino_i": "",
            "Nitta_Emi_i": "",
            "Pile_i": "",
            "Saito_Shuka_i": "",
            "Suwa_Nanaka_i": "",
            "Suzuki_Aina_i": "",
            "Takatsuki_Kanako_i": "",
            "Tokui_Sora_i": "",
            "Uchida_Aya_i": "",
            "Sato_Hinata_i": "",
            "Tano_Asami_i": "",
            "Onishi_Aguri_i": "",
            "Sagara_Mayu_i": "",
            "Maeda_Kaori_i": "",
            "Kubota_Miyu_i": "",
            "Murakami_Natsumi_i": "",
            "Kito_Akari_i": "",
            "Kusunoki_Tomori_i": "",
            "Sashide_Maria_i": "",
            "Tanaka_Chiemi_i": "",
            "Koizumi_Moeka_i": "",
            "Uchida_Shu_i": "",
            "Houmoto_Akina_i": "",
            "Yano_Hinaki_i": "",
            "Date_Sayuri_i": "",
            "Liyuu_i": "",
            "Misaki_Nako_i": "",
            "Payton_Naomi_i": "",
            "Aoyama_Nagisa_i": "",
        }